#!/usr/bin/env bash
set -e

YELLOW='\033[0;33m'
NO_COLOR='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BREW_FILE="$SCRIPT_DIR/Brewfile"

if command -v "$1" >/dev/null 2>&1 "brew"; then
  echo "Homebrew is installed."
else
  echo "Homebrew is not installed. Please install Homebrew first."
  echo "Visit https://brew.sh/ for installation instructions."
  exit 1
fi

brew update
brew bundle --file="$BREW_FILE"