#!/usr/bin/env bash

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

upgrade() {
    local tool="$1"

    echo "Using Homebrew to install $tool..."
    brew install "$tool" || brew upgrade "$tool"
}

if command_exists "brew"; then
  echo "Homebrew is installed."
else
  echo "Homebrew is not installed. Please install Homebrew first."
  echo "Visit https://brew.sh/ for installation instructions."
  exit 1
fi

upgrade jq
upgrade shellcheck
upgrade shfmt
